version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'apiTSdb'
      MYSQL_USER: 'gui'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'qwe123asd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
